kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-redirect-config
  namespace: esercito-tekton
data:
  nginx-redirect-config.conf: |-
{{- range .Values.server_routes }}
{{ . | nindent 4 }}  #la funzione nindent 4 indenta i valori da includere in questo yaml di 4 spazi. Questo per evitare errori di formattazione
{{- end }}


