kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-redirect-config
  namespace: esercito-tekton
data:
  nginx-redirect-config.conf: |
    server {
        listen 8080;
        server_name nginx-container-service-esercito-tekton.apps.lab01.gpslab.club;
        location / {
            return 301  https://spring-helloworld-app1-esercito-tekton.apps.lab01.gpslab.club;

        }
    }
    server {
        listen 8080;
        server_name nginx2-container-service-esercito-tekton.apps.lab01.gpslab.club;
        location / {
            return 301  https://spring-helloworld-app1-esercito-tekton.apps.lab01.gpslab.club;

        }
    }

