kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-redirect-config
  namespace: esercito-tekton
data:
  nginx-redirect-config.conf: |
    server {
        listen 8080;
        server_name www.spring-helloworld-route-esercito-tekton.apps.lab01.gpslab.club;
        location / {
            return 301 http://spring-helloworld-route-esercito-tekton.apps.lab01.gpslab.club/;
        }
    }

