# values-prod.yaml
replicaCount: 1
image:
  repository: quay.io/dscrimie/nginx-redirect
  tag: confd
  pullPolicy: Always
containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: https
    containerPort: 8443
    protocol: TCP
configMapName: nginx-redirect-config

server_routes: |
  server {
      listen 8080;
      server_name nginx-container-service-esercito-tekton.apps.lab01.gpslab.club;
      location / {
          return 301  https://spring-helloworld-app1-esercito-tekton.apps.lab01.gpslab.club;
      }
  }
  server {
      listen 8080;
      server_name nginx2-container-service-esercito-tekton.apps.lab01.gpslab.club;
      location / {
          return 301  https://spring-helloworld-app1-esercito-tekton.apps.lab01.gpslab.club;
      }
  }
  server {
      listen 8080;
      server_name www.spring-helloworld-app1-esercito-tekton.apps.lab01.gpslab.club;
      location / {
          return 301  https://spring-helloworld-app1-esercito-tekton.apps.lab01.gpslab.club;
      }
  }

